import { createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

// Route tree is generated by the TanStack Router Vite plugin from src/routes/**.
// Do not hand-edit routeTree.gen.ts — add/change files under src/routes instead.
export const router = createRouter({ routeTree })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
