/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetsIndexRouteImport } from './routes/widgets/index'
import { Route as WidgetsCreateRouteImport } from './routes/widgets/create'
import { Route as WidgetsWidgetIdRouteImport } from './routes/widgets/$widgetId'
import { Route as WidgetsWidgetIdEditRouteImport } from './routes/widgets/$widgetId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsIndexRoute = WidgetsIndexRouteImport.update({
  id: '/widgets/',
  path: '/widgets/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsCreateRoute = WidgetsCreateRouteImport.update({
  id: '/widgets/create',
  path: '/widgets/create',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsWidgetIdRoute = WidgetsWidgetIdRouteImport.update({
  id: '/widgets/$widgetId',
  path: '/widgets/$widgetId',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsWidgetIdEditRoute = WidgetsWidgetIdEditRouteImport.update({
  id: '/widgets/$widgetId_/edit',
  path: '/widgets/$widgetId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/widgets/$widgetId': typeof WidgetsWidgetIdRoute
  '/widgets/create': typeof WidgetsCreateRoute
  '/widgets/': typeof WidgetsIndexRoute
  '/widgets/$widgetId/edit': typeof WidgetsWidgetIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/widgets/$widgetId': typeof WidgetsWidgetIdRoute
  '/widgets/create': typeof WidgetsCreateRoute
  '/widgets': typeof WidgetsIndexRoute
  '/widgets/$widgetId/edit': typeof WidgetsWidgetIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/widgets/$widgetId': typeof WidgetsWidgetIdRoute
  '/widgets/create': typeof WidgetsCreateRoute
  '/widgets/': typeof WidgetsIndexRoute
  '/widgets/$widgetId_/edit': typeof WidgetsWidgetIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/widgets/$widgetId'
    | '/widgets/create'
    | '/widgets/'
    | '/widgets/$widgetId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/widgets/$widgetId'
    | '/widgets/create'
    | '/widgets'
    | '/widgets/$widgetId/edit'
  id:
    | '__root__'
    | '/'
    | '/widgets/$widgetId'
    | '/widgets/create'
    | '/widgets/'
    | '/widgets/$widgetId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WidgetsWidgetIdRoute: typeof WidgetsWidgetIdRoute
  WidgetsCreateRoute: typeof WidgetsCreateRoute
  WidgetsIndexRoute: typeof WidgetsIndexRoute
  WidgetsWidgetIdEditRoute: typeof WidgetsWidgetIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/': {
      id: '/widgets/'
      path: '/widgets'
      fullPath: '/widgets/'
      preLoaderRoute: typeof WidgetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/create': {
      id: '/widgets/create'
      path: '/widgets/create'
      fullPath: '/widgets/create'
      preLoaderRoute: typeof WidgetsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/$widgetId': {
      id: '/widgets/$widgetId'
      path: '/widgets/$widgetId'
      fullPath: '/widgets/$widgetId'
      preLoaderRoute: typeof WidgetsWidgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/$widgetId_/edit': {
      id: '/widgets/$widgetId_/edit'
      path: '/widgets/$widgetId/edit'
      fullPath: '/widgets/$widgetId/edit'
      preLoaderRoute: typeof WidgetsWidgetIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WidgetsWidgetIdRoute: WidgetsWidgetIdRoute,
  WidgetsCreateRoute: WidgetsCreateRoute,
  WidgetsIndexRoute: WidgetsIndexRoute,
  WidgetsWidgetIdEditRoute: WidgetsWidgetIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
